version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    ports:
      - "5500:5432"

  web:
    build: .
    container_name: django_prod
    restart: always
    environment:
      - DEBUG=False
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5500
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_prod_data:
